INSERT INTO USER(FIRST_NAME, LAST_NAME, LOGIN, PASSWORD) VALUES ('John', 'Smith', 'jsmith', 'qwerty');
INSERT INTO USER(FIRST_NAME, LAST_NAME, LOGIN, PASSWORD) VALUES ('Jane', 'Doe', 'jdoe', 'mySecret');

INSERT INTO ROOM(NAME, ROOM_NUMBER, SEAT_INFO, LOCATION, PROJECTOR, PHONE_NUMBER) VALUES ('Large Room', '1', '10', '1st floor', 'YES', '22-22-22');
INSERT INTO ROOM(NAME, ROOM_NUMBER, SEAT_INFO, LOCATION, PROJECTOR, PHONE_NUMBER) VALUES ('Medium Room', '2', '6', '1st floor', 'YES', '');
INSERT INTO ROOM(NAME, ROOM_NUMBER, SEAT_INFO, LOCATION, PROJECTOR, PHONE_NUMBER) VALUES ('Small Room', '3', '4', '2nd floor', 'NO', '');

INSERT INTO RESERVATION (ROOM_ID, USER_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = '2'), (SELECT USER_ID FROM USER WHERE FIRST_NAME = 'John'), '2019-10-15');

