CREATE TABLE ROOM(
  ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
  SEAT_INFO CHAR(2) NOT NULL,
  LOCATION VARCHAR(30),
  PROJECTOR VARCHAR(5),
  PHONE_NUMBER VARCHAR(30)

);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  LOGIN VARCHAR(20),
  PASSWORD VARCHAR(40)

);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  RES_DATE DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
